
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'AND OPEN PLAY SEARCH STOP THANKS WORD WRITE\n    searching : expression\n                | empty\n\n    \n    expression : expression expression\n    \n    expression : SEARCH\n                | OPEN\n                | WORD\n                | AND\n    \n    empty :\n    '
    
_lr_action_items = {'SEARCH':([0,2,4,5,6,7,8,],[4,4,-4,-5,-6,-7,4,]),'OPEN':([0,2,4,5,6,7,8,],[5,5,-4,-5,-6,-7,5,]),'WORD':([0,2,4,5,6,7,8,],[6,6,-4,-5,-6,-7,6,]),'AND':([0,2,4,5,6,7,8,],[7,7,-4,-5,-6,-7,7,]),'$end':([0,1,2,3,4,5,6,7,8,],[-8,0,-1,-2,-4,-5,-6,-7,-3,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'searching':([0,],[1,]),'expression':([0,2,8,],[2,8,8,]),'empty':([0,],[3,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> searching","S'",1,None,None,None),
  ('searching -> expression','searching',1,'p_searching','tokenTestFinal.py',137),
  ('searching -> empty','searching',1,'p_searching','tokenTestFinal.py',138),
  ('expression -> expression expression','expression',2,'p_expression','tokenTestFinal.py',145),
  ('expression -> SEARCH','expression',1,'p_expression_type','tokenTestFinal.py',151),
  ('expression -> OPEN','expression',1,'p_expression_type','tokenTestFinal.py',152),
  ('expression -> WORD','expression',1,'p_expression_type','tokenTestFinal.py',153),
  ('expression -> AND','expression',1,'p_expression_type','tokenTestFinal.py',154),
  ('empty -> <empty>','empty',0,'p_empty','tokenTestFinal.py',162),
]
